language: python

python: 
  - "3.9"

env:
  - SECRET_KEY=c38b65a57ac1bc32139009fb5139e2abe9d914cc3b16c01a3b
  - DEBUG=True

service:
  - redis-server

install:
  - pip install -r requirements.txt

script:
  - python -m coverage run --source='.' manage.py test .

after_success:
  - bash <(curl -s https://codecov.io/bash)